# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bogard_t/rendu/tek3/Gomoku

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bogard_t/rendu/tek3/Gomoku

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bogard_t/rendu/tek3/Gomoku/CMakeFiles /home/bogard_t/rendu/tek3/Gomoku/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bogard_t/rendu/tek3/Gomoku/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gomoku

# Build rule for target.
Gomoku: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gomoku
.PHONY : Gomoku

# fast build rule for target.
Gomoku/fast:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/build
.PHONY : Gomoku/fast

srcs/Gomoku.o: srcs/Gomoku.cpp.o

.PHONY : srcs/Gomoku.o

# target to build an object file
srcs/Gomoku.cpp.o:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/Gomoku.cpp.o
.PHONY : srcs/Gomoku.cpp.o

srcs/Gomoku.i: srcs/Gomoku.cpp.i

.PHONY : srcs/Gomoku.i

# target to preprocess a source file
srcs/Gomoku.cpp.i:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/Gomoku.cpp.i
.PHONY : srcs/Gomoku.cpp.i

srcs/Gomoku.s: srcs/Gomoku.cpp.s

.PHONY : srcs/Gomoku.s

# target to generate assembly for a file
srcs/Gomoku.cpp.s:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/Gomoku.cpp.s
.PHONY : srcs/Gomoku.cpp.s

srcs/Main.o: srcs/Main.cpp.o

.PHONY : srcs/Main.o

# target to build an object file
srcs/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/Main.cpp.o
.PHONY : srcs/Main.cpp.o

srcs/Main.i: srcs/Main.cpp.i

.PHONY : srcs/Main.i

# target to preprocess a source file
srcs/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/Main.cpp.i
.PHONY : srcs/Main.cpp.i

srcs/Main.s: srcs/Main.cpp.s

.PHONY : srcs/Main.s

# target to generate assembly for a file
srcs/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/Main.cpp.s
.PHONY : srcs/Main.cpp.s

srcs/TextureManager.o: srcs/TextureManager.cpp.o

.PHONY : srcs/TextureManager.o

# target to build an object file
srcs/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/TextureManager.cpp.o
.PHONY : srcs/TextureManager.cpp.o

srcs/TextureManager.i: srcs/TextureManager.cpp.i

.PHONY : srcs/TextureManager.i

# target to preprocess a source file
srcs/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/TextureManager.cpp.i
.PHONY : srcs/TextureManager.cpp.i

srcs/TextureManager.s: srcs/TextureManager.cpp.s

.PHONY : srcs/TextureManager.s

# target to generate assembly for a file
srcs/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/TextureManager.cpp.s
.PHONY : srcs/TextureManager.cpp.s

srcs/mSFML_Audio.o: srcs/mSFML_Audio.cpp.o

.PHONY : srcs/mSFML_Audio.o

# target to build an object file
srcs/mSFML_Audio.cpp.o:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/mSFML_Audio.cpp.o
.PHONY : srcs/mSFML_Audio.cpp.o

srcs/mSFML_Audio.i: srcs/mSFML_Audio.cpp.i

.PHONY : srcs/mSFML_Audio.i

# target to preprocess a source file
srcs/mSFML_Audio.cpp.i:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/mSFML_Audio.cpp.i
.PHONY : srcs/mSFML_Audio.cpp.i

srcs/mSFML_Audio.s: srcs/mSFML_Audio.cpp.s

.PHONY : srcs/mSFML_Audio.s

# target to generate assembly for a file
srcs/mSFML_Audio.cpp.s:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/mSFML_Audio.cpp.s
.PHONY : srcs/mSFML_Audio.cpp.s

srcs/mSFML_Window.o: srcs/mSFML_Window.cpp.o

.PHONY : srcs/mSFML_Window.o

# target to build an object file
srcs/mSFML_Window.cpp.o:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/mSFML_Window.cpp.o
.PHONY : srcs/mSFML_Window.cpp.o

srcs/mSFML_Window.i: srcs/mSFML_Window.cpp.i

.PHONY : srcs/mSFML_Window.i

# target to preprocess a source file
srcs/mSFML_Window.cpp.i:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/mSFML_Window.cpp.i
.PHONY : srcs/mSFML_Window.cpp.i

srcs/mSFML_Window.s: srcs/mSFML_Window.cpp.s

.PHONY : srcs/mSFML_Window.s

# target to generate assembly for a file
srcs/mSFML_Window.cpp.s:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/mSFML_Window.cpp.s
.PHONY : srcs/mSFML_Window.cpp.s

srcs/map.o: srcs/map.cpp.o

.PHONY : srcs/map.o

# target to build an object file
srcs/map.cpp.o:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/map.cpp.o
.PHONY : srcs/map.cpp.o

srcs/map.i: srcs/map.cpp.i

.PHONY : srcs/map.i

# target to preprocess a source file
srcs/map.cpp.i:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/map.cpp.i
.PHONY : srcs/map.cpp.i

srcs/map.s: srcs/map.cpp.s

.PHONY : srcs/map.s

# target to generate assembly for a file
srcs/map.cpp.s:
	$(MAKE) -f CMakeFiles/Gomoku.dir/build.make CMakeFiles/Gomoku.dir/srcs/map.cpp.s
.PHONY : srcs/map.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Gomoku"
	@echo "... srcs/Gomoku.o"
	@echo "... srcs/Gomoku.i"
	@echo "... srcs/Gomoku.s"
	@echo "... srcs/Main.o"
	@echo "... srcs/Main.i"
	@echo "... srcs/Main.s"
	@echo "... srcs/TextureManager.o"
	@echo "... srcs/TextureManager.i"
	@echo "... srcs/TextureManager.s"
	@echo "... srcs/mSFML_Audio.o"
	@echo "... srcs/mSFML_Audio.i"
	@echo "... srcs/mSFML_Audio.s"
	@echo "... srcs/mSFML_Window.o"
	@echo "... srcs/mSFML_Window.i"
	@echo "... srcs/mSFML_Window.s"
	@echo "... srcs/map.o"
	@echo "... srcs/map.i"
	@echo "... srcs/map.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

